SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

CREATE TABLE IF NOT EXISTS `chat_lang` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `lang` varchar(255) COLLATE utf8_bin NOT NULL,
  `map` text COLLATE utf8_bin NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=4 ;

INSERT INTO `chat_lang` (`id`, `lang`, `map`) VALUES
(2, 'en', '{\r\n  "lables": {\r\n    "chatView": {\r\n      "goToRooms": "Діалоги",\r\n      "dialog": "Діалоги",\r\n      "participants": "Учасники",\r\n      "send": "Відіслати",\r\n      "messages": "Повідомлення",\r\n      "message_placeholder": "Напишіть ваше повідомлення і натисність Enter...",\r\n      "phrases": "Сталі вирази"\r\n    },\r\n    "roomListView": {\r\n      "newRoom": "Створити діалог",\r\n      "noMessage": "Повідомлення відсутнє",\r\n      "participants": "Учасники",\r\n      "search_placeholder": "Пошук",\r\n      "addRoomModal":{\r\n          "close":"Закрити",\r\n          "create":"Створити",\r\n          "title":"Створення діалогу",\r\n          "room_name_placeholder":"Назва кімнати"\r\n      },\r\n      "filters":{\r\n        "anonim":"Анонімні",\r\n        "private":"Приватні",\r\n        "consultation":"Консультації"\r\n      }\r\n    },\r\n	"formBuilder":{\r\n	"button":"кнопка",\r\n	"input":"текстове поле",\r\n  "codePromt":"HTML код:",\r\n  "update":"Оновити",\r\n  "status":"Статус",\r\n  "description":"Опис",\r\n  "lang":"Мова",\r\n  "labels":"Мітки",\r\n  "values":"Значення",\r\n  "legend":"Легенда",\r\n  "isradio":"Радіо-кнопка",\r\n  "tools":"Інструменти",\r\n  "properties":"Властивості",\r\n  "addFormToDB":"Додати форму в базу"\r\n	}\r\n  },\r\n  "ratings": {\r\n    "global": "Наскільки все файно",\r\n    "smart": "Наскільки все заумно"\r\n  },\r\n  "fileOperations":{\r\n  "fileSizeOverflowLimit":"Файл перевищує максимальний розмір",\r\n  "fileEmpty":"Порожній файл",\r\n  "fileUploaded": "Файл успішно завантажено",\r\n  "fileNotFound":"Файл не знайдено"\r\n  }\r\n}'),
(3, 'ua', '{\r\n  "lables": {\r\n    "chatView": {\r\n      "goToRooms": "Діалоги",\r\n      "dialog": "Діалоги",\r\n      "participants": "Учасники",\r\n      "send": "Відіслати",\r\n      "messages": "Повідомлення",\r\n      "message_placeholder": "Напишіть ваше повідомлення і натисність Enter...",\r\n      "phrases": "Сталі вирази"\r\n    },\r\n    "roomListView": {\r\n      "newRoom": "Створити діалог",\r\n      "noMessage": "Повідомлення відсутнє",\r\n      "participants": "Учасники",\r\n      "search_placeholder": "Пошук",\r\n      "addRoomModal":{\r\n          "close":"Закрити",\r\n          "create":"Створити",\r\n          "title":"Створення діалогу",\r\n          "room_name_placeholder":"Назва кімнати"\r\n      },\r\n      "filters":{\r\n        "anonim":"Анонімні",\r\n        "private":"Приватні",\r\n        "consultation":"Консультації"\r\n      }\r\n    },\r\n	"formBuilder":{\r\n	"button":"кнопка",\r\n	"input":"текстове поле",\r\n  "codePromt":"HTML код:",\r\n  "update":"Оновити",\r\n  "status":"Статус",\r\n  "description":"Опис",\r\n  "lang":"Мова",\r\n  "labels":"Мітки",\r\n  "values":"Значення",\r\n  "legend":"Легенда",\r\n  "isradio":"Радіо-кнопка",\r\n  "tools":"Інструменти",\r\n  "properties":"Властивості",\r\n  "addFormToDB":"Додати форму в базу"\r\n	}\r\n  },\r\n  "ratings": {\r\n    "global": "Наскільки все файно",\r\n    "smart": "Наскільки все заумно"\r\n  },\r\n  "fileOperations":{\r\n  "fileSizeOverflowLimit":"Файл перевищує максимальний розмір",\r\n  "fileEmpty":"Порожній файл",\r\n  "fileUploaded": "Файл успішно завантажено",\r\n  "fileNotFound":"Файл не знайдено"\r\n  }\r\n}');